[package]
name = "ani-link"
version = "0.3.7"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
crossterm = { version = "0.29.0", features = ["event-stream"] }
dirs = "6.0.0"
figment = { version = "0.10.19", features = ["toml", "env"] }
futures = "0.3.31"
rust-fuzzy-search = "0.1.1"
itertools = "0.14.0"
notify-rust = "4.11.7"
ratatui = "0.29.0"
rayon = "1.11.0"
regex = "1.11.2"
reqwest = { version = "0.12.23", features = ["cookies", "blocking"] }
serde = { version = "1.0.219", features = ["serde_derive"] }
strum = "0.27.2"
strum_macros = "0.27.2"
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.5"
