[package]
name = "ani-link"
version = "0.2.1"
edition = "2021"

[dependencies]
async-trait = "0.1.88"
clap = { version = "4.5.38", features = ["derive"] }
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
futures = "0.3.31"
itertools = "0.14.0"
regex = "1.11.1"
reqwest = { version = "0.12.15" }
scraper = "0.23.1"
tokio = { version = "1.45.1", features = ["full"] }
