[package]
name = "ani-link"
version = "0.3.4"
edition = "2021"

[profile.dev]
opt-level = 1

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
crossterm = { version = "0.29.0", features = ["event-stream"] }
dirs = "6.0.0"
figment = { version = "0.10.19", features = ["toml", "env"] }
futures = "0.3.31"
fuzzy-matcher = "0.3.7"
itertools = "0.14.0"
notify-rust = "4.11.7"
ratatui = "0.29.0"
regex = "1.11.1"
reqwest = { version = "0.12.22", features = ["cookies"] }
scraper = "0.23.1"
serde = { version = "1.0.219", features = ["serde_derive"] }
strum = "0.27.1"
strum_macros = "0.27.1"
tokio = { version = "1.46.1", features = ["full"] }
toml = "0.9.2"
