[package]
name = "ani-link"
version = "0.2.2"
edition = "2021"

[profile.dev]
opt-level = 1

[dependencies]
async-trait = "0.1.88"
clap = { version = "4.5.39", features = ["derive"] }
crossterm = "0.29.0"
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
dirs = "6.0.0"
figment = { version = "0.10.19", features = ["toml", "env"] }
futures = "0.3.31"
itertools = "0.14.0"
ratatui = "0.29.0"
regex = "1.11.1"
reqwest = { version = "0.12.18" }
scraper = "0.23.1"
serde = { version = "1.0.219", features = ["serde_derive"] }
strum = "0.27.1"
strum_macros = "0.27.1"
tokio = { version = "1.45.1", features = ["full"] }
toml = "0.8.22"
